name: Build LaTeX document
on: 
  push: 
    branches: 
      - main
  create:
      tags:
        - v*
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          glob_root_file: true
          latexmk_use_xelatex: true
      - uses: actions/upload-artifact@v2
        with:
          name: cv-gabriel-faundez
          path: cv-gabriel-faundez.pdf
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: '${{ secrets.AUTH_PROVIDER  }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'
      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: './'
          destination: '${{ secrets.BUCKET_NAME }}/curriculum'
          predefinedAcl: 'publicRead'
          glob: '*.pdf'
        